# Arduino Makefile
# 1. Place this file in the directory with TestMake.ino
# 2. run 'make'
# 3. run 'make upload'

ARDUINO_DIR  = /usr/share/arduino
TARGET       = TestMake
BOARD_TAG    = uno
ARDUINO_PORT = /dev/ttyACM0
ARDUINO_LIBS = 
include /usr/share/arduino/Arduino.mk